package middleware

const (
	RequestedModel        = "requested_model"
	PublicModel           = "public_model"
	PublicCapabilityModel = "public_capability_model"
	ResolvedCapability    = "resolved_capability"
	ChannelID             = "channel_id"
	Group                 = "group"
	Token                 = "token"
	GroupBalance          = "group_balance"
	RequestModel          = "request_model"
	PublicRequestModel    = "public_request_model"
	RoutingModel          = "routing_model"
	VideoCapability       = "video_capability"
	RequestUser           = "request_user"
	RequestMetadata       = "request_metadata"
	PromptCacheKey        = "prompt_cache_key"
	RequestServiceTier    = "request_service_tier"
	RequestAt             = "request_at"
	RequestID             = "request_id"
	ModelCaches           = "model_caches"
	ModelConfig           = "model_config"
	Mode                  = "mode"
	JobID                 = "job_id"
	GenerationID          = "generation_id"
	OperationID           = "operation_id"
	ResponseID            = "response_id"
	VideoID               = "video_id"
	FileID                = "file_id"

	requestBodyNode = "request_body_node"
)
