// Package ownedimage persists generated bytes before exposing a customer result.
package ownedimage

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"github.com/labring/aiproxy/core/common/imagecapabilities"
	_ "golang.org/x/image/webp"
	"image"
	_ "image/gif"
	_ "image/jpeg"
	_ "image/png"
	"io"
	"net"
	"net/http"
	"net/url"
	"os"
	"strconv"
	"strings"
	"time"
)

const MaxBytes = 10 * 1024 * 1024

var ErrStorage = errors.New("generated image storage failed")

// Permanent delivery failure: retrying the same bytes cannot reduce their size.
var ErrTooLarge = errors.New("generated image exceeds archive size limit")

type archiveIdentityKey struct{}
type auxiliaryNameKey struct{}

// WithAuxiliaryName scopes an owned mask to its parent output without counting it as another generation.
func WithAuxiliaryName(ctx context.Context, name string) context.Context {
	return context.WithValue(ctx, auxiliaryNameKey{}, name)
}
func AuxiliaryName(ctx context.Context) string {
	name, _ := ctx.Value(auxiliaryNameKey{}).(string)
	return name
}

type archiveIdentity struct {
	taskID string
	index  int
}

// WithArchiveIdentity gives retried uploads a stable key in temporary storage.
func WithArchiveIdentity(ctx context.Context, taskID string, index int) context.Context {
	return context.WithValue(ctx, archiveIdentityKey{}, archiveIdentity{taskID: taskID, index: index})
}

// Uses the existing trusted engine-to-app connection, never a request-provided host.
func Configured() bool {
	return os.Getenv("EXTERNAL_BALANCE_URL") != "" || os.Getenv("PUBLIC_IMAGE_BASE_URL") != ""
}

func publicIP(ip net.IP) bool {
	for _, cidr := range []string{"100.64.0.0/10", "192.0.0.0/24", "192.0.2.0/24", "198.18.0.0/15", "198.51.100.0/24", "203.0.113.0/24"} {
		_, block, _ := net.ParseCIDR(cidr)
		if block.Contains(ip) {
			return false
		}
	}
	return ip.IsGlobalUnicast() && !ip.IsPrivate() && !ip.IsLoopback() && !ip.IsLinkLocalUnicast() && !ip.IsUnspecified()
}
func downloadClient() *http.Client {
	return &http.Client{Timeout: 30 * time.Second, CheckRedirect: noRedirect, Transport: &http.Transport{
		MaxResponseHeaderBytes: 1 << 20,
		DialContext: func(ctx context.Context, network, address string) (net.Conn, error) {
			host, port, err := net.SplitHostPort(address)
			if err != nil || port != "443" {
				return nil, ErrStorage
			}
			ips, err := net.DefaultResolver.LookupIPAddr(ctx, host)
			if err != nil || len(ips) == 0 {
				return nil, ErrStorage
			}
			for _, ip := range ips {
				if !publicIP(ip.IP) {
					return nil, ErrStorage
				}
			}
			return (&net.Dialer{}).DialContext(ctx, network, net.JoinHostPort(ips[0].IP.String(), port))
		},
	}}
}
func noRedirect(*http.Request, []*http.Request) error { return http.ErrUseLastResponse }

func Store(ctx context.Context, source string) (string, string, error) {
	client := downloadClient()
	defer client.CloseIdleConnections()
	return store(ctx, source, os.Getenv("EXTERNAL_BALANCE_URL"), os.Getenv("EXTERNAL_BALANCE_KEY"), client, &http.Client{Timeout: 30 * time.Second, CheckRedirect: noRedirect})
}

type Metadata struct {
	Width       int
	Height      int
	ContentType string
}

func Inspect(data []byte) Metadata {
	config, _, err := image.DecodeConfig(bytes.NewReader(data))
	if err != nil {
		return Metadata{ContentType: http.DetectContentType(data)}
	}
	return Metadata{Width: config.Width, Height: config.Height, ContentType: http.DetectContentType(data)}
}
func StoreWithMetadata(ctx context.Context, source string) (string, Metadata, error) {
	client := downloadClient()
	defer client.CloseIdleConnections()
	var metadata Metadata
	url, _, err := storeWithMetadata(ctx, source, os.Getenv("EXTERNAL_BALANCE_URL"), os.Getenv("EXTERNAL_BALANCE_KEY"), client, &http.Client{Timeout: 30 * time.Second, CheckRedirect: noRedirect}, &metadata)
	return url, metadata, err
}

// DeleteArchivedImage removes only the object identified by this completed
// task and output slot. The application validates the scoped key independently.
func DeleteArchivedImage(ctx context.Context, taskID string, index int, contentType string) error {
	return deleteArchivedImage(ctx, os.Getenv("EXTERNAL_BALANCE_URL"), os.Getenv("EXTERNAL_BALANCE_KEY"), taskID, index, contentType, &http.Client{Timeout: 15 * time.Second, CheckRedirect: noRedirect})
}

func deleteArchivedImage(ctx context.Context, base, key, taskID string, index int, contentType string, client *http.Client) error {
	destination, err := url.Parse(base)
	if err != nil || destination.Host == "" || (destination.Scheme != "https" && destination.Scheme != "http") || destination.User != nil || destination.RawQuery != "" || destination.Fragment != "" || key == "" {
		return ErrStorage
	}
	if index < 0 || index >= imagecapabilities.MaxOutputs || taskID == "" {
		return ErrStorage
	}
	bodyFields := map[string]any{"taskId": taskID, "outputIndex": index, "contentType": contentType}
	if name := AuxiliaryName(ctx); name != "" {
		if !imagecapabilities.ValidAuxiliaryImageName(name) {
			return ErrStorage
		}
		bodyFields["auxiliaryName"] = name
	}
	body, err := json.Marshal(bodyFields)
	if err != nil {
		return ErrStorage
	}
	endpoint := strings.TrimRight(base, "/") + "/api/internal/media/images"
	request, err := http.NewRequestWithContext(ctx, http.MethodDelete, endpoint, bytes.NewReader(body))
	if err != nil {
		return ErrStorage
	}
	request.Header.Set("Authorization", "Bearer "+key)
	request.Header.Set("Content-Type", "application/json")
	response, err := client.Do(request)
	if err != nil {
		return ErrStorage
	}
	defer response.Body.Close()
	if response.StatusCode != http.StatusOK {
		return ErrStorage
	}
	var result struct {
		Code int `json:"code"`
	}
	if json.NewDecoder(io.LimitReader(response.Body, 1024)).Decode(&result) != nil || result.Code != 0 {
		return ErrStorage
	}
	return nil
}
func store(ctx context.Context, source, base, key string, download, upload *http.Client) (string, string, error) {
	return storeWithMetadata(ctx, source, base, key, download, upload, nil)
}
func storeWithMetadata(ctx context.Context, source, base, key string, download, upload *http.Client, metadata *Metadata) (string, string, error) {
	fail := func() (string, string, error) { return "", "", ErrStorage }
	target, err := url.Parse(source)
	if err != nil || target.Scheme != "https" || target.Hostname() == "" || target.User != nil || target.Fragment != "" || (target.Port() != "" && target.Port() != "443") {
		return fail()
	}
	destination, err := url.Parse(base)
	if err != nil || destination.Host == "" || (destination.Scheme != "https" && destination.Scheme != "http") || destination.User != nil || destination.RawQuery != "" || destination.Fragment != "" || key == "" {
		return fail()
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, source, nil)
	if err != nil {
		return fail()
	}
	response, err := download.Do(request)
	if err != nil {
		return fail()
	}
	defer response.Body.Close()
	if response.ContentLength > MaxBytes {
		return "", "", ErrTooLarge
	}
	if response.StatusCode != 200 {
		return fail()
	}
	data, err := io.ReadAll(io.LimitReader(response.Body, MaxBytes+1))
	if len(data) > MaxBytes {
		return "", "", ErrTooLarge
	}
	if err != nil || len(data) == 0 {
		return fail()
	}
	mime := http.DetectContentType(data)
	if mime != "image/jpeg" && mime != "image/png" && mime != "image/webp" && mime != "image/gif" {
		return fail()
	}
	inspected := Inspect(data)
	if mime == "image/gif" && (inspected.Width <= 0 || inspected.Height <= 0) {
		return fail()
	}
	if metadata != nil {
		*metadata = inspected
	}
	endpoint := strings.TrimRight(base, "/") + "/api/internal/media/images"
	request, err = http.NewRequestWithContext(ctx, http.MethodPost, endpoint, bytes.NewReader(data))
	if err != nil {
		return fail()
	}
	request.Header.Set("Authorization", "Bearer "+key)
	request.Header.Set("Content-Type", mime)
	if name := AuxiliaryName(ctx); name != "" {
		if !imagecapabilities.ValidAuxiliaryImageName(name) {
			return fail()
		}
		if _, ok := ctx.Value(archiveIdentityKey{}).(archiveIdentity); !ok {
			return fail()
		}
		request.Header.Set("X-Musespan-Image-Auxiliary-Name", name)
	}
	if identity, ok := ctx.Value(archiveIdentityKey{}).(archiveIdentity); ok {
		request.Header.Set("X-Musespan-Image-Task-ID", identity.taskID)
		request.Header.Set("X-Musespan-Image-Output-Index", strconv.Itoa(identity.index))
	}
	stored, err := upload.Do(request)
	if err != nil {
		return fail()
	}
	defer stored.Body.Close()
	if stored.StatusCode != 200 {
		return fail()
	}
	var result struct {
		Code int `json:"code"`
		Data struct {
			URL string `json:"url"`
		} `json:"data"`
	}
	if json.NewDecoder(io.LimitReader(stored.Body, 16384)).Decode(&result) != nil || result.Code != 0 {
		return fail()
	}
	owned, err := url.Parse(result.Data.URL)
	if err != nil || owned.Scheme != "https" || owned.Hostname() == "" || owned.User != nil || owned.Fragment != "" {
		return fail()
	}
	return result.Data.URL, mime, nil
}
